#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Motor,  port1,           firstMotor,    tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,           secondMotor,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           thirdMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          flashlight,    tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    int greens = 0; //set integer greens equal to 0
	while(true)     //forever loop
	{
		if (greens < 1)     //if greens is less than 1
		{
			startMotor(secondMotor, 50); //start secondMotor at speed 50
			wait(8);                     //continue for 8 seconds
			stopMotor(secondMotor);      //stop secondMotor
			greens += 1;                 //add one to greens
		}
		turnFlashlightOn(flashlight, 100); //turn the flashlight on at full power
		int first = 0;                     //set int first equal to 0
		if (first < 1)                     //if first is less than 1
		{
			startMotor(firstMotor, 75); //start firstMotor at 75 power
			wait(0.08);                 //continue for 0.08 seconds
			stopMotor(firstMotor);      //stop firstMotor
			wait(5);                    //wait 5 seconds
			first += 1;                 //add one to first
		}
		else //otherwise
		{
			startMotor(firstMotor, 35); //start firstMotor at 35 power
			wait(0.03);                 //continue for 0.03 second
			stopMotor(firstMotor);      //stop firstMotor
			wait(5);                    //wait 5 seconds
		}
		if(SensorValue(lineFollower) <= 2910) //for white measured at 2900
		{
			startMotor(thirdMotor, 50);     //start thirdMotor at 50 power
			wait(0.13);                     //wait 0.13 second
			stopMotor(thirdMotor);          //stop thirdMotor
			startMotor(secondMotor, 127);   //start secondMotor at full power
			wait(0.1);                      //continue for 0.1 second
			stopMotor(secondMotor);         //stop secondMotor
			wait(2);                        //wait 2 seconds
			startMotor(thirdMotor, -50);    //start thirdMotor at -50 power
			wait(0.13);                     //continue for 0.13 second
			stopMotor(thirdMotor);          //stop thirdMotor
		}
		else if(SensorValue(lineFollower) >= 2920) //for gray measured at 2932
		{
			startMotor(thirdMotor, -50);    //start thirdMotor at -50 power
			wait(0.13);                     //wait 0.13 second
			stopMotor(thirdMotor);          //stop thirdMotor
			startMotor(secondMotor, 127);   //start secondMotor at full power
			wait(0.1);                      //continue for 0.1 second
			stopMotor(secondMotor);         //stop secondMotor
			wait(2);                        //wait 2 seconds
			startMotor(thirdMotor, 50);     //start thirdMotor at 50 power
			wait(0.13);                     //continue for 0.13 second
			stopMotor(thirdMotor);          //stop thirdMotor
		}
	}
}